---
# Install Docker and DVWA on webservers
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:
  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 80:80
      restart_policy: always

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes

# Configure Elk VM
- name: Config Elk VM with Docker
  hosts: elk
  remote_user: azadmin
  become: true
  tasks:
  - name: Use more memory
    sysctl:
      name: vm.max_map_count
      value: '262144'
      state: present
      reload: yes

  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      published_ports:
       - "5601:5601"
       - "9200:9200"
       - "5044:5044"
      restart_policy: always

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes

# Install Filebeat on Webservers
- name: Install and Launch Filebeat
  hosts: webservers
  become: true
  tasks:
  - name: download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: Install filebeat .deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: Copy filebeat-config.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable filebeat system module
    command: filebeat modules enable system

  - name: Setup filebeat
    command: filebeat setup

  - name: Start filebeat service
    command: service filebeat start

  - name: Enable filebeat service on boot
    systemd:
      name: filebeat
      enabled: yes

# Install Metricbeat on Webservers
- name: Install and Launch Metricbeat
  hosts: webservers
  become: true
  tasks:
  - name: download metricbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat .deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Copy metricbeat-config.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable metricbeat docker module
    command: metricbeat modules enable docker

  - name: Setup metricbeat
    command: metricbeat setup

  - name: Enable metricbeat service on boot
    systemd:
      name: metricbeat
      enabled: yes

